# -*- coding: utf-8 -*-

# logging
LOGGING_JSON = 'logging.json'
TARGET_HANDLERS = ['console', ]

# flask config
CONFIG_CFG = 'config.cfg'
DEFAULT_ORION_ENDPOINT = 'DEFAULT_ORION_ENDPOINT'
DEFAULT_PORT = 'DEFAULT_PORT'
DEFAULT_BEARER_AUTH = 'DEFAULT_BEARER_AUTH'

# environment variable name
LOG_LEVEL = 'LOG_LEVEL'
LISTEN_PORT = 'LISTEN_PORT'
BEARER_AUTH = 'BEARER_AUTH'
PREFIX = 'PREFIX'
MONGODB_ENDPOINT = 'MONGODB_ENDPOINT'
MONGODB_REPLICASET = 'MONGODB_REPLICASET'
MONGODB_DATABASE = 'MONGODB_DATABASE'
MONGODB_COLLECTION = 'MONGODB_COLLECTION'
CYGNUS_MONGO_ATTR_PERSISTENCE = 'CYGNUS_MONGO_ATTR_PERSISTENCE'
